Update omv-ci.yml

diff --git a/.github/workflows/omv-ci.yml b/.github/workflows/omv-ci.yml
--- a/.github/workflows/omv-ci.yml
+++ b/.github/workflows/omv-ci.yml
@@ -41,6 +41,17 @@ jobs:
       run: |
         omv all -V --engine=${{ matrix.engine }}
         
+    - name: Run additional tests 
+      run: |
+        if [[ ${OMV_ENGINE} == "jNeuroML" || ${OMV_ENGINE} == "jNeuroML_NEURON" ]]; then echo "Continuing with test after jNeuroML/jNeuroML_NEURON is run..."; else exit $OMV_SUCCESS; fi
+        echo "Running more tests..."
+        omv list -V 
+        cd NeuroML2
+        ls -alt
+        python spikes.py ${OMV_ENGINE}
+        python spikesFast.py ${OMV_ENGINE}
+        exit $OMV_SUCCESS # in case it failed above...
+        
     - name: OMV final version info
       run: |
         omv list -V # list installed engines
